//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xin.AQS.SyncNationalAQIPublishDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AQIDataPublishLive", Namespace="http://schemas.datacontract.org/2004/07/SyncNationalAQIPublishDataService")]
    [System.SerializableAttribute()]
    public partial class AQIDataPublishLive : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AQIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeasureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO2_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string O3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string O3_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string O3_8hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string O3_8h_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM10_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM2_5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM2_5_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryPollutantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SO2_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimePointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnheathfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AQI {
            get {
                return this.AQIField;
            }
            set {
                if ((object.ReferenceEquals(this.AQIField, value) != true)) {
                    this.AQIField = value;
                    this.RaisePropertyChanged("AQI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO {
            get {
                return this.COField;
            }
            set {
                if ((object.ReferenceEquals(this.COField, value) != true)) {
                    this.COField = value;
                    this.RaisePropertyChanged("CO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_24h {
            get {
                return this.CO_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_24hField, value) != true)) {
                    this.CO_24hField = value;
                    this.RaisePropertyChanged("CO_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Measure {
            get {
                return this.MeasureField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasureField, value) != true)) {
                    this.MeasureField = value;
                    this.RaisePropertyChanged("Measure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO2 {
            get {
                return this.NO2Field;
            }
            set {
                if ((object.ReferenceEquals(this.NO2Field, value) != true)) {
                    this.NO2Field = value;
                    this.RaisePropertyChanged("NO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO2_24h {
            get {
                return this.NO2_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.NO2_24hField, value) != true)) {
                    this.NO2_24hField = value;
                    this.RaisePropertyChanged("NO2_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string O3 {
            get {
                return this.O3Field;
            }
            set {
                if ((object.ReferenceEquals(this.O3Field, value) != true)) {
                    this.O3Field = value;
                    this.RaisePropertyChanged("O3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string O3_24h {
            get {
                return this.O3_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.O3_24hField, value) != true)) {
                    this.O3_24hField = value;
                    this.RaisePropertyChanged("O3_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string O3_8h {
            get {
                return this.O3_8hField;
            }
            set {
                if ((object.ReferenceEquals(this.O3_8hField, value) != true)) {
                    this.O3_8hField = value;
                    this.RaisePropertyChanged("O3_8h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string O3_8h_24h {
            get {
                return this.O3_8h_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.O3_8h_24hField, value) != true)) {
                    this.O3_8h_24hField = value;
                    this.RaisePropertyChanged("O3_8h_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM10 {
            get {
                return this.PM10Field;
            }
            set {
                if ((object.ReferenceEquals(this.PM10Field, value) != true)) {
                    this.PM10Field = value;
                    this.RaisePropertyChanged("PM10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM10_24h {
            get {
                return this.PM10_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.PM10_24hField, value) != true)) {
                    this.PM10_24hField = value;
                    this.RaisePropertyChanged("PM10_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM2_5 {
            get {
                return this.PM2_5Field;
            }
            set {
                if ((object.ReferenceEquals(this.PM2_5Field, value) != true)) {
                    this.PM2_5Field = value;
                    this.RaisePropertyChanged("PM2_5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM2_5_24h {
            get {
                return this.PM2_5_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.PM2_5_24hField, value) != true)) {
                    this.PM2_5_24hField = value;
                    this.RaisePropertyChanged("PM2_5_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PositionName {
            get {
                return this.PositionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionNameField, value) != true)) {
                    this.PositionNameField = value;
                    this.RaisePropertyChanged("PositionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryPollutant {
            get {
                return this.PrimaryPollutantField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryPollutantField, value) != true)) {
                    this.PrimaryPollutantField = value;
                    this.RaisePropertyChanged("PrimaryPollutant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quality {
            get {
                return this.QualityField;
            }
            set {
                if ((object.ReferenceEquals(this.QualityField, value) != true)) {
                    this.QualityField = value;
                    this.RaisePropertyChanged("Quality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SO2 {
            get {
                return this.SO2Field;
            }
            set {
                if ((object.ReferenceEquals(this.SO2Field, value) != true)) {
                    this.SO2Field = value;
                    this.RaisePropertyChanged("SO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SO2_24h {
            get {
                return this.SO2_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.SO2_24hField, value) != true)) {
                    this.SO2_24hField = value;
                    this.RaisePropertyChanged("SO2_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationCode {
            get {
                return this.StationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StationCodeField, value) != true)) {
                    this.StationCodeField = value;
                    this.RaisePropertyChanged("StationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimePoint {
            get {
                return this.TimePointField;
            }
            set {
                if ((this.TimePointField.Equals(value) != true)) {
                    this.TimePointField = value;
                    this.RaisePropertyChanged("TimePoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unheathful {
            get {
                return this.UnheathfulField;
            }
            set {
                if ((object.ReferenceEquals(this.UnheathfulField, value) != true)) {
                    this.UnheathfulField = value;
                    this.RaisePropertyChanged("Unheathful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityAQIPublishLive", Namespace="http://schemas.datacontract.org/2004/07/SyncNationalAQIPublishDataService")]
    [System.SerializableAttribute()]
    public partial class CityAQIPublishLive : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AQIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeasureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string O3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM2_5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryPollutantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimePointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnheathfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AQI {
            get {
                return this.AQIField;
            }
            set {
                if ((object.ReferenceEquals(this.AQIField, value) != true)) {
                    this.AQIField = value;
                    this.RaisePropertyChanged("AQI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO {
            get {
                return this.COField;
            }
            set {
                if ((object.ReferenceEquals(this.COField, value) != true)) {
                    this.COField = value;
                    this.RaisePropertyChanged("CO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityCode {
            get {
                return this.CityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CityCodeField, value) != true)) {
                    this.CityCodeField = value;
                    this.RaisePropertyChanged("CityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Measure {
            get {
                return this.MeasureField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasureField, value) != true)) {
                    this.MeasureField = value;
                    this.RaisePropertyChanged("Measure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO2 {
            get {
                return this.NO2Field;
            }
            set {
                if ((object.ReferenceEquals(this.NO2Field, value) != true)) {
                    this.NO2Field = value;
                    this.RaisePropertyChanged("NO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string O3 {
            get {
                return this.O3Field;
            }
            set {
                if ((object.ReferenceEquals(this.O3Field, value) != true)) {
                    this.O3Field = value;
                    this.RaisePropertyChanged("O3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM10 {
            get {
                return this.PM10Field;
            }
            set {
                if ((object.ReferenceEquals(this.PM10Field, value) != true)) {
                    this.PM10Field = value;
                    this.RaisePropertyChanged("PM10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM2_5 {
            get {
                return this.PM2_5Field;
            }
            set {
                if ((object.ReferenceEquals(this.PM2_5Field, value) != true)) {
                    this.PM2_5Field = value;
                    this.RaisePropertyChanged("PM2_5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryPollutant {
            get {
                return this.PrimaryPollutantField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryPollutantField, value) != true)) {
                    this.PrimaryPollutantField = value;
                    this.RaisePropertyChanged("PrimaryPollutant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quality {
            get {
                return this.QualityField;
            }
            set {
                if ((object.ReferenceEquals(this.QualityField, value) != true)) {
                    this.QualityField = value;
                    this.RaisePropertyChanged("Quality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SO2 {
            get {
                return this.SO2Field;
            }
            set {
                if ((object.ReferenceEquals(this.SO2Field, value) != true)) {
                    this.SO2Field = value;
                    this.RaisePropertyChanged("SO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimePoint {
            get {
                return this.TimePointField;
            }
            set {
                if ((this.TimePointField.Equals(value) != true)) {
                    this.TimePointField = value;
                    this.RaisePropertyChanged("TimePoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unheathful {
            get {
                return this.UnheathfulField;
            }
            set {
                if ((object.ReferenceEquals(this.UnheathfulField, value) != true)) {
                    this.UnheathfulField = value;
                    this.RaisePropertyChanged("Unheathful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityDayAQIPublishLive", Namespace="http://schemas.datacontract.org/2004/07/SyncNationalAQIPublishDataService")]
    [System.SerializableAttribute()]
    public partial class CityDayAQIPublishLive : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AQIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CO_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeasureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO2_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string O3_8h_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM10_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PM2_5_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryPollutantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SO2_24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimePointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnheathfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AQI {
            get {
                return this.AQIField;
            }
            set {
                if ((object.ReferenceEquals(this.AQIField, value) != true)) {
                    this.AQIField = value;
                    this.RaisePropertyChanged("AQI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CO_24h {
            get {
                return this.CO_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.CO_24hField, value) != true)) {
                    this.CO_24hField = value;
                    this.RaisePropertyChanged("CO_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityCode {
            get {
                return this.CityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CityCodeField, value) != true)) {
                    this.CityCodeField = value;
                    this.RaisePropertyChanged("CityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Measure {
            get {
                return this.MeasureField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasureField, value) != true)) {
                    this.MeasureField = value;
                    this.RaisePropertyChanged("Measure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO2_24h {
            get {
                return this.NO2_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.NO2_24hField, value) != true)) {
                    this.NO2_24hField = value;
                    this.RaisePropertyChanged("NO2_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string O3_8h_24h {
            get {
                return this.O3_8h_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.O3_8h_24hField, value) != true)) {
                    this.O3_8h_24hField = value;
                    this.RaisePropertyChanged("O3_8h_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM10_24h {
            get {
                return this.PM10_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.PM10_24hField, value) != true)) {
                    this.PM10_24hField = value;
                    this.RaisePropertyChanged("PM10_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PM2_5_24h {
            get {
                return this.PM2_5_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.PM2_5_24hField, value) != true)) {
                    this.PM2_5_24hField = value;
                    this.RaisePropertyChanged("PM2_5_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryPollutant {
            get {
                return this.PrimaryPollutantField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryPollutantField, value) != true)) {
                    this.PrimaryPollutantField = value;
                    this.RaisePropertyChanged("PrimaryPollutant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quality {
            get {
                return this.QualityField;
            }
            set {
                if ((object.ReferenceEquals(this.QualityField, value) != true)) {
                    this.QualityField = value;
                    this.RaisePropertyChanged("Quality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SO2_24h {
            get {
                return this.SO2_24hField;
            }
            set {
                if ((object.ReferenceEquals(this.SO2_24hField, value) != true)) {
                    this.SO2_24hField = value;
                    this.RaisePropertyChanged("SO2_24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimePoint {
            get {
                return this.TimePointField;
            }
            set {
                if ((this.TimePointField.Equals(value) != true)) {
                    this.TimePointField = value;
                    this.RaisePropertyChanged("TimePoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unheathful {
            get {
                return this.UnheathfulField;
            }
            set {
                if ((object.ReferenceEquals(this.UnheathfulField, value) != true)) {
                    this.UnheathfulField = value;
                    this.RaisePropertyChanged("Unheathful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SyncNationalAQIPublishDataService.ISyncNationalAQIPublishDataService")]
    public interface ISyncNationalAQIPublishDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncNationalAQIPublishDataService/GetAQIDataPublishLive", ReplyAction="http://tempuri.org/ISyncNationalAQIPublishDataService/GetAQIDataPublishLiveRespon" +
            "se")]
        Xin.AQS.SyncNationalAQIPublishDataService.AQIDataPublishLive[] GetAQIDataPublishLive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncNationalAQIPublishDataService/GetAQIDataPublishHistory", ReplyAction="http://tempuri.org/ISyncNationalAQIPublishDataService/GetAQIDataPublishHistoryRes" +
            "ponse")]
        Xin.AQS.SyncNationalAQIPublishDataService.AQIDataPublishLive[] GetAQIDataPublishHistory(System.DateTime beginTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncNationalAQIPublishDataService/GetCityAQIPublishLive", ReplyAction="http://tempuri.org/ISyncNationalAQIPublishDataService/GetCityAQIPublishLiveRespon" +
            "se")]
        Xin.AQS.SyncNationalAQIPublishDataService.CityAQIPublishLive[] GetCityAQIPublishLive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncNationalAQIPublishDataService/GetCityAQIPublishHistory", ReplyAction="http://tempuri.org/ISyncNationalAQIPublishDataService/GetCityAQIPublishHistoryRes" +
            "ponse")]
        Xin.AQS.SyncNationalAQIPublishDataService.CityAQIPublishLive[] GetCityAQIPublishHistory(System.DateTime beginTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncNationalAQIPublishDataService/GetCityDayAQIPublishLive", ReplyAction="http://tempuri.org/ISyncNationalAQIPublishDataService/GetCityDayAQIPublishLiveRes" +
            "ponse")]
        Xin.AQS.SyncNationalAQIPublishDataService.CityDayAQIPublishLive[] GetCityDayAQIPublishLive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncNationalAQIPublishDataService/GetCityDayAQIPublishHistory" +
            "", ReplyAction="http://tempuri.org/ISyncNationalAQIPublishDataService/GetCityDayAQIPublishHistory" +
            "Response")]
        Xin.AQS.SyncNationalAQIPublishDataService.CityDayAQIPublishLive[] GetCityDayAQIPublishHistory(System.DateTime beginTime, System.DateTime endTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISyncNationalAQIPublishDataServiceChannel : Xin.AQS.SyncNationalAQIPublishDataService.ISyncNationalAQIPublishDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SyncNationalAQIPublishDataServiceClient : System.ServiceModel.ClientBase<Xin.AQS.SyncNationalAQIPublishDataService.ISyncNationalAQIPublishDataService>, Xin.AQS.SyncNationalAQIPublishDataService.ISyncNationalAQIPublishDataService {
        
        public SyncNationalAQIPublishDataServiceClient() {
        }
        
        public SyncNationalAQIPublishDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SyncNationalAQIPublishDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncNationalAQIPublishDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncNationalAQIPublishDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Xin.AQS.SyncNationalAQIPublishDataService.AQIDataPublishLive[] GetAQIDataPublishLive() {
            return base.Channel.GetAQIDataPublishLive();
        }
        
        public Xin.AQS.SyncNationalAQIPublishDataService.AQIDataPublishLive[] GetAQIDataPublishHistory(System.DateTime beginTime, System.DateTime endTime) {
            return base.Channel.GetAQIDataPublishHistory(beginTime, endTime);
        }
        
        public Xin.AQS.SyncNationalAQIPublishDataService.CityAQIPublishLive[] GetCityAQIPublishLive() {
            return base.Channel.GetCityAQIPublishLive();
        }
        
        public Xin.AQS.SyncNationalAQIPublishDataService.CityAQIPublishLive[] GetCityAQIPublishHistory(System.DateTime beginTime, System.DateTime endTime) {
            return base.Channel.GetCityAQIPublishHistory(beginTime, endTime);
        }
        
        public Xin.AQS.SyncNationalAQIPublishDataService.CityDayAQIPublishLive[] GetCityDayAQIPublishLive() {
            return base.Channel.GetCityDayAQIPublishLive();
        }
        
        public Xin.AQS.SyncNationalAQIPublishDataService.CityDayAQIPublishLive[] GetCityDayAQIPublishHistory(System.DateTime beginTime, System.DateTime endTime) {
            return base.Channel.GetCityDayAQIPublishHistory(beginTime, endTime);
        }
    }
}
